// End-to-end proof of the daily workflow, run in a throwaway copy of the site
// so fixture content can never reach the repository or a deployment.
//
//   A. a batch adds a sixth page and a draft; a reviewer approves only the sixth
//      -> the sixth is built, routed, in the sitemap and the homepage navigation;
//         the draft is nowhere
//   B. the navigation limit drops below the catalog -> the guide index appears
//   C. a batch withdraws the sixth -> it disappears from output, routes, sitemap,
//      navigation and related links (the output is rebuilt clean)
//
// Every step uses the real tools (seo.mjs, generate-routes.mjs, build-site.mjs,
// verify-site.mjs). Pass --keep to leave the copy for inspection.

import { cpSync, existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import assert from 'node:assert/strict';

const app = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const site = resolve(app, '../..');
const SKIP = new Set(['.git', 'node_modules', '.seo-dist', '.seo-dist.building', '.vercel', '.next', 'out', '.release']);
const work = mkdtempSync(join(tmpdir(), 'revo-seo-fixture-'));
const keep = process.argv.includes('--keep');

cpSync(site, work, {
  recursive: true,
  filter: source => {
    const parts = relative(site, source).split(sep);
    if (parts.some(part => SKIP.has(part))) return false;
    // seo/app/public is regenerated by the build
    return !(parts[0] === 'seo' && parts[1] === 'app' && parts[2] === 'public');
  },
});

const run = (cmd, args, cwd = work) => execFileSync(cmd, args, { cwd, stdio: ['ignore', 'pipe', 'pipe'], encoding: 'utf8' });
const seo = (...args) => run(process.execPath, ['seo/app/tools/seo.mjs', ...args]);
const step = label => console.log(`\n== ${label}`);
const out = path => join(work, '.seo-dist', path);
const read = path => readFileSync(out(path), 'utf8');
const vercelSources = () => JSON.parse(readFileSync(join(work, 'vercel.json'), 'utf8')).rewrites.map(r => r.source);
const setLimit = limit => {
  const file = join(work, 'seo/app/site.config.json');
  writeFileSync(file, JSON.stringify({ ...JSON.parse(readFileSync(file, 'utf8')), navigationLimit: limit }) + '\n');
};
function release() {
  console.log('  ' + run(process.execPath, ['seo/app/tools/generate-routes.mjs']).trim());
  const built = run(process.execPath, ['tools/build-site.mjs'], join(work, 'seo/app'));
  console.log('  ' + built.trim().split('\n').filter(line => line.startsWith('PASS')).join('\n  '));
  console.log('  ' + run(process.execPath, ['tools/verify-site.mjs'], join(work, 'seo/app')).trim());
}

const SIXTH = '/ai-answering-service/weekend-calls';
const DRAFT = '/ai-answering-service/holiday-calls';
const INDEX = '/ai-answering-service';
const sitemapHas = path => read('sitemap.xml').includes(`<loc>https://www.revoapp.ai${path}</loc>`);
const homeLinks = () => [...read('index.html').match(/<nav data-revo-call-planning[^>]*>(.*?)<\/nav>/s)[1].matchAll(/href="([^"]+)"/g)].map(m => m[1]);

try {
  // The six-guide boundary fixture starts from five guides, independently of catalog growth.
  const fixtureRegistry = join(work, 'seo/shared/data/landing-pages.json');
  writeFileSync(fixtureRegistry, JSON.stringify(JSON.parse(readFileSync(fixtureRegistry, 'utf8')).slice(0, 5), null, 2) + '\n');
  step('install locked dependencies in the copy');
  run('npm', ['--prefix', 'seo/app', 'ci', '--no-audit', '--no-fund']);

  step('A. batch adds a sixth page and a draft; only the sixth is approved');
  console.log('  ' + seo('apply', 'seo/shared/fixtures/2026-10-09-fixture-sixth-and-draft.json').trim().replaceAll('\n', '\n  '));
  console.log('  ' + seo('apply', 'seo/shared/fixtures/2026-10-09-fixture-sixth-and-draft.json').trim());
  console.log('  ' + seo('approve', 'weekend-calls', '--reviewer', 'Fixture Reviewer').trim());
  release();
  assert.ok(existsSync(out(SIXTH.slice(1) + '.html')), 'sixth page built');
  assert.ok(vercelSources().includes(SIXTH), 'sixth page routed');
  assert.ok(sitemapHas(SIXTH), 'sixth page in sitemap');
  assert.ok(homeLinks().includes(SIXTH), 'sixth page in homepage navigation');
  assert.ok(!existsSync(out(DRAFT.slice(1) + '.html')), 'draft not built');
  assert.ok(!vercelSources().includes(DRAFT) && !sitemapHas(DRAFT) && !homeLinks().includes(DRAFT), 'draft not routed, listed or linked');
  assert.ok(!existsSync(out('ai-answering-service.html')), 'no index while the navigation holds every guide');
  console.log(`  ok: ${SIXTH} built, routed, in sitemap and navigation; ${DRAFT} absent everywhere`);

  step('B. navigation limit 5 < 6 approved guides: the guide index appears');
  setLimit(5);
  release();
  assert.ok(existsSync(out('ai-answering-service.html')), 'index built');
  assert.ok(vercelSources().includes(INDEX) && sitemapHas(INDEX), 'index routed and in sitemap');
  assert.deepEqual(homeLinks().length, 6, 'five guides plus the index link');
  assert.equal(homeLinks().at(-1), INDEX);
  assert.ok(read('ai-answering-service.html').includes(`href="${SIXTH}"`), 'index lists the sixth page');
  assert.ok(!read('ai-answering-service.html').includes(`href="${DRAFT}"`), 'index does not list the draft');
  console.log('  ok: homepage links 5 guides + "All call guides"; index lists all 6 approved guides');

  step('C. batch withdraws the sixth page; the output is rebuilt clean');
  setLimit(6);
  console.log('  ' + seo('apply', 'seo/shared/fixtures/2026-10-10-fixture-withdraw.json').trim().replaceAll('\n', '\n  '));
  release();
  assert.ok(!existsSync(out(SIXTH.slice(1) + '.html')) && !existsSync(out(SIXTH.slice(1) + '.txt')), 'withdrawn page removed from output');
  assert.ok(!vercelSources().includes(SIXTH) && !sitemapHas(SIXTH) && !homeLinks().includes(SIXTH), 'withdrawn page unrouted and unlisted');
  assert.ok(!existsSync(out('ai-answering-service.html')), 'index removed again');
  for (const page of ['after-hours', 'missed-calls', 'cost-of-missed-calls']) assert.ok(!read(`ai-answering-service/${page}.html`).includes(`href="${SIXTH}"`), `no related link to the withdrawn page on ${page}`);
  console.log(`  ok: ${SIXTH} gone from output, vercel.json, sitemap, navigation and related links`);

  step('status of the fixture registry');
  console.log('  ' + seo('status').trim().replaceAll('\n', '\n  '));
  console.log('\nPASS fixture end-to-end: sixth page published, draft excluded, index on growth, withdrawal cleaned');
} finally {
  if (keep) console.log(`\n(kept ${work})`);
  else rmSync(work, { recursive: true, force: true });
}
